SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_C_COMPILER /opt/armv7l-unknown-linux-gnueabihf/bin/armv7l-unknown-linux-gnueabihf-gcc)
SET(CMAKE_CXX_COMPILER /opt/armv7l-unknown-linux-gnueabihf/bin/armv7l-unknown-linux-gnueabihf-g++)
SET(CMAKE_FIND_ROOT_PATH  /opt/armv7l-unknown-linux-gnueabihf)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)